---
- name: Simple configuration
  hosts: all
  connection: local
  gather_facts: no
  vars:
      conf_dir: "{{ playbook_dir }}/.compiled/"

  pre_tasks:
     - name: Set some global facts
       set_fact:
          host_tmpdir: "{{ conf_dir}}/{{ inventory_hostname}}"
       changed_when: no
       check_mode: no
     - name: Make sure there are no remains from a previous run
       file:
         path: "{{ host_tmpdir }}"
         state: absent
       changed_when: no
       check_mode: no
     - name: Create folder to store configurations and diffs for/from the devices
       file:
         path: "{{ host_tmpdir }}"
         state: directory
       changed_when: no
       check_mode: no

- name: Automated Configuration
  hosts: all
  connection: local
  roles:
    - base
    - ip

  post_tasks:
    - name: Assemble all the configuration bits
      assemble:
          src: "{{ host_tmpdir }}/"
          dest: "{{ host_tmpdir }}/assembled.conf"
      check_mode: no
      changed_when: no
    - name: Load configuration into the device
      napalm_install_config:
        hostname: "{{ host }}"
        username: "{{ user }}"
        dev_os: "{{ os }}"
        password: "{{ password }}"
        optional_args:
          port: "{{ port }}"
        config_file: "{{ host_tmpdir }}/assembled.conf"
        commit_changes: "{{ not ansible_check_mode }}"
        replace_config: false
        get_diffs: true
        diff_file: "{{ host_tmpdir }}/diff"
      tags: [print_action]
    - include: includes/validate.yaml
      when: not ansible_check_mode
